pull_request_rules:
  - name: automatic merge
    actions:
      merge:
        strict: true
    conditions:
    - label!=work-in-progress
    - '#approved-reviews-by>=1'
    - status-success=continuous-integration/travis-ci/pr
  - name: automatic merge from pyup
    actions:
      merge:
        strict: true
    conditions:
    - author=pyup-bot
    - label!=work-in-progress
    - status-success=continuous-integration/travis-ci/pr
